### ISSUE TITLE
Add NextSimpleStarter

### ISSUE THREAD

**Issue by ooade** [unicodeveloper/awesome-nextjs#1]
I'm not sure what category this would fall under, because it's more of a boilerplate than just a regular app. 

Repo: https://github.com/ooade/NextSimpleStarter

**Comment by unicodeveloper** [comment]
You can create a boilerplate/starter section in your pr and include it
there. WDYT?

**Comment by ooade** [comment]
Yeah, Boilerplates/Starters will definitely be fine
