### ISSUE TITLE
Add next-boilerplate

### ISSUE THREAD

**Issue by arefaslani** [unicodeveloper/awesome-nextjs#52]
Could you add our boilerplate named [Next Boilerplate](https://arefaslani.github.io/next-boilerplate) to the boilerplates list?

**Comment by unicodeveloper** [comment]
Please submit a PR

**Comment by unicodeveloper** [comment]
Closing this in favor of [#53](https://github.com/unicodeveloper/awesome-nextjs/pull/53)
